apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 9090
      - name: flask
        image: tiangolo/uwsgi-nginx:python3.8
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        env:
          - name: FLASK_APP
            value: flaskPython.py